"""init2

Revision ID: 2beb6a2abc6b
Revises: eb64f9178476
Create Date: 2022-07-22 10:38:05.207420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2beb6a2abc6b'
down_revision = 'eb64f9178476'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
